version: "3.9"

services:
  # PostgreSQL database service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123  # Database password (replace with actual password)
      POSTGRES_DB: budget_app  # Database name (replace with actual name)
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data (optional)
    ports:
          - 5432:5432

volumes:
  postgres-data:  # Named volume for database persistence (optional)
